# Generated by Django 4.1.3 on 2023-08-26 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cour',
            fields=[
                ('id_cour', models.AutoField(primary_key=True, serialize=False)),
                ('cour', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Group_td',
            fields=[
                ('id_goup', models.AutoField(primary_key=True, serialize=False)),
                ('groupe', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id_salle', models.AutoField(primary_key=True, serialize=False)),
                ('salle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Seance_cour',
            fields=[
                ('id_seance_cour', models.AutoField(primary_key=True, serialize=False)),
                ('date_debut', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seance_TD',
            fields=[
                ('id_seance_td', models.AutoField(primary_key=True, serialize=False)),
                ('date_debut', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cour', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='emplois_temps.cour')),
            ],
        ),
    ]
