# Generated by Django 4.1.3 on 2023-08-31 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emplois_temps', '0003_cour_niveau'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='seance_cour',
            table='tblevents',
        ),
    ]
