# Generated by Django 4.1.3 on 2023-09-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplois_temps', '0005_alter_seance_td_cour_alter_seance_td_enseignant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance_td',
            name='color',
            field=models.CharField(default='black', max_length=100),
        ),
    ]
