# Generated by Django 4.1.3 on 2023-09-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplois_temps', '0006_seance_td_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance_cour',
            name='color',
            field=models.CharField(default='red', max_length=100),
        ),
    ]
