# Generated by Django 4.1.3 on 2023-09-03 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emplois_temps', '0008_alter_seance_cour_filiere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seance_cour',
            name='color',
        ),
        migrations.RemoveField(
            model_name='seance_td',
            name='color',
        ),
    ]
