# Generated by Django 4.1.3 on 2023-08-26 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id_ufr', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id_filiere', models.AutoField(primary_key=True, serialize=False)),
                ('filiere', models.CharField(max_length=100)),
                ('departement', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departement.departement')),
            ],
        ),
    ]
